name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the artifact file
        required: true
        type: string
    outputs:
      result:
        description: Result of the deploy operation
        value: ${{ jobs.deploy.outputs.outcome }}
jobs:    
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output Info
        run: echo "Deploying and uploading"
      - name: Set output value
        id: set-result
        run: echo "step-result=SUCCESS" >> $GITHUB_OUTPUT